/*
 * Generate schemas/transformer.schema.json and schemas/params.schema.json from
 * the transformer kit and the registry.
 *
 *   npm run build:schemas            write them
 *   npm run build:schemas -- --check fail if the committed files are out of date
 *
 * Runs under vite-node, because the registry imports modules with Vite's `?url`
 * suffix. The generated files are never edited by hand.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { KINDS } from "../transformers/_kit/index.js";
import { DEFS, paramsSchema } from "../transformers/_kit/value-schemas.js";
import { PALETTE_GROUPS, REGISTRY } from "../transformers/index.js";

const BASE = "https://github.com/regislon/geomarmot/schemas";
const text = { type: "string" };
const strings = (minItems = 0) => ({ type: "array", minItems, items: text });
const port = {
  type: "object",
  additionalProperties: false,
  required: ["id", "label", "description"],
  properties: { id: { type: "string", pattern: "^[a-z][A-Za-z0-9_]*$" }, label: text, description: text },
};

export function transformerSchema() {
  const option = {
    type: "object",
    additionalProperties: false,
    required: ["value", "description"],
    properties: { value: text, description: text },
  };
  const param = {
    type: "object",
    additionalProperties: false,
    required: ["id", "label", "kind", "sql", "description", "value"],
    properties: {
      id: { type: "string", pattern: "^[a-z][A-Za-z0-9_]*$" },
      label: text,
      kind: { enum: Object.keys(KINDS) },
      sql: { enum: ["none", "literal", "identifier", "expression", "query"] },
      description: text,
      default: {},
      value: { description: "The JSON Schema of the param's value." },
      example: {},
      options: { type: "array", items: option },
      optionsFrom: text,
      choices: strings(),
      units: text,
      conditional: { type: "boolean" },
    },
  };
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `${BASE}/transformer.schema.json`,
    title: "GeoMarmot transformer (catalogue entry)",
    description:
      "A transformer's declaration without its hooks, as the catalogue, the assistant and generated transformers see it. Generated by scripts/build-schemas.js.",
    type: "object",
    additionalProperties: false,
    required: ["id", "name", "group", "role", "summary", "description", "inputs", "outputs", "params"],
    properties: {
      id: { type: "string", pattern: "^[A-Z][A-Za-z0-9]*$" },
      name: text,
      group: { enum: PALETTE_GROUPS },
      role: { enum: ["transform", "source", "sink"] },
      summary: { type: "string", minLength: 20, maxLength: 160 },
      description: text,
      whenToUse: strings(2),
      whenNotToUse: strings(1),
      keywords: strings(3),
      examples: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["input", "params", "output"],
          properties: { input: text, params: text, output: text },
        },
      },
      inputs: { type: "array", items: port },
      outputs: { type: "array", items: port },
      outputsDependOnParams: { type: "boolean" },
      params: { type: "array", items: param },
      paramsVersion: { type: "integer", minimum: 1 },
      aiUsable: { type: "boolean" },
    },
  };
}

export function paramsSchemas() {
  const byTransformer = {};
  for (const id of [...REGISTRY.keys()].sort()) {
    const transformer = REGISTRY.get(id);
    if (PALETTE_GROUPS.includes(transformer.group)) byTransformer[id] = paramsSchema(transformer);
  }
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `${BASE}/params.schema.json`,
    title: "GeoMarmot transformer params",
    description:
      "The params object of each transformer, by id, under $defs. Every property is optional: params are merged over the transformer's defaults. Generated by scripts/build-schemas.js.",
    $defs: { ...DEFS, ...byTransformer },
  };
}

const FILES = {
  "schemas/transformer.schema.json": transformerSchema,
  "schemas/params.schema.json": paramsSchemas,
};

const render = (schema) => `${JSON.stringify(schema, null, 2)}\n`;

const check = process.argv.includes("--check");
const stale = [];
for (const [path, build] of Object.entries(FILES)) {
  const wanted = render(build());
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current === wanted) continue;
  if (check) stale.push(path);
  else writeFileSync(path, wanted);
}
if (stale.length) {
  console.error(`Out of date: ${stale.join(", ")}. Run npm run build:schemas.`);
  process.exit(1);
}
